wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 80
optimizer:
  desc: null
  value: rmsprop
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1709795423.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.5
      5: 0.16.4
      6: 4.32.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
